### ISSUE TITLE
Edit the script for multiple outputs without concatenate?

### ISSUE THREAD

**Issue by krigeta** [brennier/extract-dialogue#3]
Hello, what line should I change so it won't merge the audio into one audio file?
Like multiple outputs according to the subtitle timestamps.

Sorry if it is a beginner question but I am a beginner.

Thank you

**Comment by brennier** [comment]
The script in its current state cannot be easily edited to do that. Instead of cutting the video into a bunch of audio files and then concatenating them, this script builds an ffmpeg filter complex that does the whole process in one step. This approach is faster, more efficient, and less-error prone (since it doesn't have to deal with insufficient space errors, overwriting files, identifying which audio files should be concatenated, etc).

However, there is a previous version of this script that does create intermediate audio files and then concatenates them afterwards. I've modified that version so that it does what you ask. You can find the modification [here](https://gist.github.com/brennier/d7f1f33b171dfb9d451f3c7cc9287a7a). In this version, all of the intermediate files get saved in the same folder that you run the script. The files are named after the timestamp that they start at. The files 'subs.ass' and 'list.txt' also get created, but you can discard these after running the script.

**Comment by krigeta** [comment]
Thanks Fam you saved my day. thank you so much for both of the awesome scripts. <3
